# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.runs/synth_1/.Xil/Vivado-30260-Elias/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z010clg400-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_vhdl -lib xil_defaultlib {
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/JR_detect.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/alu.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/alu_control.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/alu_parcial.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/barrel_shifter.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/control1.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/control_branch.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/general.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/control_prog.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/decodificador.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/divisorCLK.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/entrada.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/exten_signo_cero.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/md.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/md_io.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/mi.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/mux32.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/mux32_4a1.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/mux5_4a1.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/pc.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/prog.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/reg.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/salida_par.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/shift_left.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/shift_left16.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/shift_left_j.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/suma_4.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/sumador32.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/uart_rx.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/uart_tx.vhd
      C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.srcs/sources_1/imports/MIPS-2023/mips.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.runs/synth_1/.Xil/Vivado-30260-Elias/realtime/mips_synth.xdc
    rt::sdcChecksum
    set rt::top mips
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/Elias/OneDrive/UCA/9_Semestre/Micro_2/Vivado/contadorcito/contadorcito.runs/synth_1/.Xil/Vivado-30260-Elias/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    rt::set_parameter incrementalOnCache ""
    rt::set_parameter doIncremental false
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
   return -code "error" $rt::result
 }
}
